### ISSUE TITLE
As a developer, I want to run load tests to determine benchmark capacity

### ISSUE THREAD

**Issue by ig-grant** [happner/happner-cluster#41]

**Comment by nomilous** [comment]
done benchmarking cluster replication capacity which measures replication time as a function of cluster size in a controlled manner: 

https://docs.google.com/document/d/1DIYV9duoViclPcwZsgM28o3oCrCzykm4-v202S-uZPc/edit#heading=h.jgjlhp4o0ko9

now to measure though-put capacity (how much load can it handle)
