### ISSUE TITLE
As a devops, I am able to deploy a complete cluster of N nodes

### ISSUE THREAD

**Issue by southbite** [happner/happner-cluster#45]
Spin up a multi-container cluster, from the command-line or script.

**Comment by ig-grant** [comment]
This is being handled by the following:

Ansible
manages the orchestration of deployments to remote hosts

Docker
manages the building of images on the remote hosts, and starting a container

**Comment by ig-grant** [comment]
This has proven to take longer than initially thought to configure and test - should probably have been sized at S5. Last few tasks are to ensure that the correct ENV vars are being injected into each container and that mesh instances are able to talk to each other.
