### ISSUE TITLE
As a developer, I want to spin up a multi-process cluster, and test message integrity using a random actibity generator

### ISSUE THREAD

**Issue by southbite** [happner/happner-cluster#46]
Spin up multiple processes via spawn, each process is a cluster node. Then we want attach a websocket happn-3 to each node. 

Then we want to pass the array of clients to something that wraps the random-activity-generator, random activity happens, and we verify that all removes and sets produce events that go to all of the clients listening to the events. 

compare on operation log

https://github.com/happner/happn-random-activity-generator/blob/master/test/test.js#L331

**Comment by nomilous** [comment]
Not doing this as a test. No need, it tests set and get and remove, all have nothing to do with cluster. 

The only thing that the cluster does is replicate, on(), which cannot be tested with the existing random activity generator.
