### ISSUE TITLE
Domains: as a happner-2 server I must be able to support happner-1 meshes and clients, behind a load balancer

### ISSUE THREAD

**Issue by southbite** [happner/happner-cluster#61]
As per the design document:
https://docs.google.com/document/d/1kgS9GpHUieNmsj1qlBNk5s0-fWM_NV2fbdFyGf0j0mM/edit#bookmark=id.j7rf0adhfudm

We want to be able to introduce a domain name which groups functionality and gives nodes in a happner cluster an address which survives load-balanced connections.

**Comment by ig-grant** [comment]
Acceptance criteria:

CLIENT:
=====
- calls component methods on the server
- subscribes to events on the server
- uses data (?)

ENDPOINT:
======
- calls component methods on the server
- subscribes to events on the server
- uses data (?)

**Comment by ig-grant** [comment]
@JensEggers, @southbite

Can you confirm the following? There is a question around what component data means in the context of the cluster:

To summarise Data within the cluster:
-------------------------------
- up until now, __component data__ WITHIN A MESH is private to the component (accessed via injected $happn context)
- Q: component data WITHIN A CLUSTER - **what does this mean?**
  - is this shared between all components of the same type within the cluster?
- __shared data__ is shared between all components within a mesh AS WELL AS WITHIN THE CLUSTER
