### ISSUE TITLE
happner-2 enhancement: local events

### ISSUE THREAD

**Issue by southbite** [happner/happner-cluster#69]
- cannot do this with wildcards
 - need to run eventemitter for intra-proc processes
 - eventemitter as its own property on the component-instance

- subscribe
  check if we are subscribing on a wildcard, if so subscribe via happn as per normal
  check if we are subscribing to a local component,  if so subscribe using   eventemitter

 - on emit:
   local eventemitter does emit always fires
   introduce options, if (local:true) return;
   else we emit event over happn as per current functionality

Back-to-front compatibility (spend hour):
TESTING HAPPNER-2 CLIENTS -> HAPPNER SERVERS

**Comment by nomilous** [comment]
This has been achieved using standard node event emitter. Does not use happn. See [local event api](https://github.com/happner/happner-2/blob/master/docs/local-event.md) doc
