### ISSUE TITLE
As a happner-client, I want to establish a connection to a happner cluster

### ISSUE THREAD

**Issue by ig-grant** [happner/happner-cluster#77]
- establish a connection to the happner cluster
- emit connection status changes
- disconnect from the happner cluster
- ability to switch connections if current connection is dropped

**Comment by southbite** [comment]
Per cluster peer, we have a single instance of the client, passed the orchestration object containing a list of peers. 

(1) method called via $happn exchange on a component
(2) interrogates peers for list of descriptions
(3) first matching description that matches method is run
(4) as other descriptions come back the list is updated

We have a dictionary of descriptions, that gets updated when peers join or when they depart.
