### ISSUE TITLE
As a happner client, I need to access data

### ISSUE THREAD

**Issue by leebow** [happner/happner-cluster#79]
Questions:
- the previous client saved data on the root, but in the new client, there is no root
- data will be nested within the component path
- what do we do with this?
- DISCUSSION...

**Comment by southbite** [comment]
We need to understand what data will be for the new happner setup.

(1) Shared data - this is data that is accessible system-wide
(2) Component data ($happn.data) - this is data that is accessible component-wide @Simon: to veryify how this works currently

The new happn client needs to be able work with both sets of data, and a facility for permissions for system-wide data needs to be provided for in happner.
