### ISSUE TITLE
Server name changes - TO DISCUSS

### ISSUE THREAD

**Issue by leebow** [happner/happner-cluster#92]
We've noticed that there is no existing functionality in happn/happner to allow for name changes on the server. So if a server changes it's name (ie: in the config) and there are existing event subscriptions, the client will stop receiving events (ie: client will just go 'quiet'). Additionally, the exchange function calls will stop replying.

**Comment by nomilous** [comment]
The was pertaining to client connected to server with name X and the server restart on (on same port) with new name, the reconnecting client restores subscriptions with the wrong name.

No longer relevant since clients now use cluster `domain` in subscription paths
